namespace ServiceTokenApi.Options
{
    /// <summary>
    /// Strongly-typed configuration for the Flitt (pay.flitt.com) embedded-checkout integration.
    /// Bound from the "Flitt" section of configuration. Secret values should be supplied through
    /// user-secrets / environment variables rather than committed appsettings in production.
    /// </summary>
    public class FlittOptions
    {
        public const string SectionName = "Flitt";

        /// <summary>Base URL of the Flitt payment API, trailing slash required (e.g. https://pay.flitt.com/api/).</summary>
        public string BaseUrl { get; set; } = "https://pay.flitt.com/api/";

        /// <summary>Merchant unique id, generated by Flitt (test value: 1549901).</summary>
        public int MerchantId { get; set; }

        /// <summary>Payment secret key used for the purchase flow (test value: "test"). Used to build / verify signatures.</summary>
        public string SecretKey { get; set; } = string.Empty;

        /// <summary>Payment secret key used for the payout flow (test value: "testcredit"). Reserved for future payout support.</summary>
        public string PayoutSecretKey { get; set; } = string.Empty;

        /// <summary>ISO currency code for payments (GEL, USD, EUR...).</summary>
        public string Currency { get; set; } = "GEL";

        /// <summary>
        /// Server-to-server callback Flitt POSTs to when an order reaches a final status.
        /// Must be publicly reachable in production. In local development the callback cannot
        /// reach localhost, so the client poll (GetStatus) reconciles status via the Flitt
        /// order-status API instead.
        /// </summary>
        public string ServerCallbackUrl { get; set; } = string.Empty;

        /// <summary>
        /// Page Flitt redirects to if a hard redirect is required (e.g. some 3-D Secure flows).
        /// This should point at a backend endpoint (api/Payment/Return) — Flitt redirects there via
        /// POST, which nginx cannot serve for the static SPA. The endpoint then bounces the browser
        /// (as a GET) to <see cref="ClientReturnUrl"/>. With the embedded checkout the buyer normally
        /// stays on the merchant page, so this whole path is only a fallback.
        /// </summary>
        public string ResponseUrl { get; set; } = string.Empty;

        /// <summary>
        /// The SPA result page the api/Payment/Return endpoint redirects the browser to (GET),
        /// e.g. https://investor.service-tokens.com/payment/return. The order id is appended as a
        /// query string so the page can poll the payment status.
        /// </summary>
        public string ClientReturnUrl { get; set; } = string.Empty;

        /// <summary>Order lifetime in seconds (how long the checkout token stays payable).</summary>
        public int LifetimeSeconds { get; set; } = 36000;
    }
}
